# Use the official Python image as the base image
FROM python:latest

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire Flask app
COPY . .

# Expose the port the Flask app runs on
EXPOSE 8223

# Start the Flask app
CMD ["python", "app.py"]