
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
      - 80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "8223:8223"
    expose:
      - 8223
      - 80
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development